# Generated by Django 4.1.2 on 2022-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfilesin',
            table='ideanestfiles',
        ),
    ]
