# Generated by Django 4.1.2 on 2022-11-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadfilesin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfilesin',
            table='infiles',
        ),
    ]
