# Generated by Django 4.1.2 on 2022-11-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_uploadfilesin_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfilesin',
        ),
    ]
